"""Add type column to steps

Revision ID: a120f850ef1e
Revises: c9cbf1c8cfb9
Create Date: 2026-02-02 09:44:10.620582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a120f850ef1e"
down_revision: str | Sequence[str] | None = "c9cbf1c8cfb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "steps",
        sa.Column(
            "type", sa.String(length=50), nullable=False, server_default="thought"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("steps", "type")
    # ### end Alembic commands ###
