"""Add cost_records table

Revision ID: dac39b3aed0c
Revises: a120f850ef1e
Create Date: 2026-02-02 17:22:59.759254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac39b3aed0c'
down_revision: Union[str, Sequence[str], None] = 'a120f850ef1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('best_unit_cost', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_records')
    # ### end Alembic commands ###
