"""align_traces_schema

Revision ID: 6a5fb04a4024
Revises: f189942f2103
Create Date: 2026-02-10 21:08:41.291365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a5fb04a4024"
down_revision: Union[str, Sequence[str], None] = "f189942f2103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE tracetype AS ENUM ('TOOL_START', 'TOOL_END', 'LLM_START', 'LLM_END', 'LOG', 'ERROR', 'EVENT')"
    )

    op.add_column(
        "traces",
        sa.Column(
            "trace_type",
            sa.Enum(
                "TOOL_START",
                "TOOL_END",
                "LLM_START",
                "LLM_END",
                "LOG",
                "ERROR",
                "EVENT",
                name="tracetype",
            ),
            nullable=False,
        ),
    )
    op.add_column("traces", sa.Column("name", sa.String(), nullable=True))
    op.add_column("traces", sa.Column("content", sa.String(), nullable=True))
    op.add_column("traces", sa.Column("metadata", sa.JSON(), nullable=True))
    op.add_column("traces", sa.Column("feedback_score", sa.Integer(), nullable=True))
    op.add_column("traces", sa.Column("feedback_comment", sa.String(), nullable=True))
    op.drop_column("traces", "raw_trace")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "traces",
        sa.Column(
            "raw_trace",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("traces", "feedback_comment")
    op.drop_column("traces", "feedback_score")
    op.drop_column("traces", "metadata")
    op.drop_column("traces", "content")
    op.drop_column("traces", "name")
    op.drop_column("traces", "trace_type")

    op.execute("DROP TYPE tracetype")

    # ### end Alembic commands ###
