"""add_user_session_id_to_traces_and_assets

Revision ID: 7be6f88205bb
Revises: 2b7c4d8e9f20
Create Date: 2026-03-02 17:23:53.322164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7be6f88205bb"
down_revision: Union[str, Sequence[str], None] = "2b7c4d8e9f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_session_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_assets_user_session_id"), ["user_session_id"], unique=False
        )

    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_session_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_traces_user_session_id"), ["user_session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traces_user_session_id"))
        batch_op.drop_column("user_session_id")

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_user_session_id"))
        batch_op.drop_column("user_session_id")

    # ### end Alembic commands ###
