"""Add episode trace and asset models

Revision ID: b5f3ce2a7b6d
Revises: 5b673a27de1b
Create Date: 2026-02-07 16:15:09.640262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f3ce2a7b6d"
down_revision: str | Sequence[str] | None = "5b673a27de1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="episodestatus"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("skill_git_hash", sa.String(), nullable=True),
        sa.Column("template_versions", sa.JSON(), nullable=True),
        sa.Column("metadata_vars", sa.JSON(), nullable=True),
        sa.Column("todo_list", sa.JSON(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("plan", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "VIDEO",
                "MJCF",
                "IMAGE",
                "STEP",
                "STL",
                "PYTHON",
                "OTHER",
                name="assettype",
            ),
            nullable=False,
        ),
        sa.Column("s3_path", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "traces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("langfuse_trace_id", sa.String(), nullable=True),
        sa.Column("raw_trace", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traces")
    op.drop_table("assets")
    op.drop_table("episodes")
    # ### end Alembic commands ###
