openapi: 3.0.3
info:
  title: MuJoCo Simulation Engine API
  description: Physics validation backend for Agentic CAD.
  version: 0.1.0
paths:
  /simulate:
    post:
      summary: Run a physics simulation
      operationId: run_simulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationRequest'
      responses:
        '200':
          description: Simulation completed (success or failure outcome)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationResponse'
        '400':
          description: Invalid input (e.g. malformed STEP)
        '500':
          description: Internal server error

components:
  schemas:
    SimulationRequest:
      type: object
      required:
        - env_geometry_step
        - agent_geometry_step
        - control_script
      properties:
        id:
          type: string
          format: uuid
        env_geometry_step:
          type: string
          description: Base64 encoded STEP file of environment
        agent_geometry_step:
          type: string
          description: Base64 encoded STEP file of agent mechanism
        control_script:
          type: string
          description: Python source code for agent controller
        config:
          $ref: '#/components/schemas/TaskConfig'

    TaskConfig:
      type: object
      properties:
        duration:
          type: number
          default: 10.0
        timestep:
          type: number
          default: 0.002
        seed:
          type: integer
          default: 42
        return_trace:
          type: boolean
          default: false

    SimulationResponse:
      type: object
      required:
        - status
        - metrics
      properties:
        request_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [SUCCESS, FAIL_COLLISION, FAIL_TIMEOUT, FAIL_MECHANICAL, SYSTEM_ERROR]
        metrics:
          $ref: '#/components/schemas/SimulationMetrics'
        error:
          type: string

    SimulationMetrics:
      type: object
      properties:
        completion_time:
          type: number
        energy_joules:
          type: number
        goal_distance_min:
          type: number
