# generated by datamodel-codegen:
#   filename:  container_schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class JobStatus(StrEnum):
    QUEUED = 'queued'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    CANCELLED = 'cancelled'


class JobType(StrEnum):
    COMMAND = 'command'
    SCRIPT = 'script'


class ToolExecutionStatus(StrEnum):
    SUCCESS = 'success'
    ERROR = 'error'


class ToolName(StrEnum):
    WRITE_FILE = 'write_file'
    EDIT_FILE = 'edit_file'
    PREVIEW_DESIGN = 'preview_design'
    VERIFY_SOLUTION = 'verify_solution'
    SEARCH_DOCS = 'search_docs'
    SEARCH_PARTS = 'search_parts'
    PREVIEW_PART = 'preview_part'
    ANALYZE_DESIGN = 'analyze_design'
    RUN_COMMAND = 'run_command'
    LINT_SCRIPT = 'lint_script'
    START_SESSION = 'start_session'
    STOP_SESSION = 'stop_session'
    VIEW_FILE = 'view_file'


class ToolRequest(BaseModel):
    """
    Request payload for executing a tool.
    """

    tool_name: ToolName = Field(..., description='Name of the tool to execute')
    arguments: dict[str, Any] | None = Field(
        None, description='Arguments for the tool', title='Arguments'
    )


class ToolResponse(BaseModel):
    """
    Response payload from a tool execution.
    """

    output: str = Field(..., description='String output from the tool', title='Output')
    error: str | None = Field(
        None, description='Error message if execution failed', title='Error'
    )
    status: ToolExecutionStatus | None = Field(
        'success', description='Status of the execution: success/error'
    )


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class JobRequest(BaseModel):
    """
    Unified request for async jobs.
    """

    type: JobType = Field(..., description="Type of job: 'command' or 'script'")
    command: str | None = Field(
        None, description='Command to run (if type=command)', title='Command'
    )
    script_name: str | None = Field(
        None, description='Script to run (if type=script)', title='Script Name'
    )
    args: list[str] | None = Field(
        None, description='Arguments for script', title='Args'
    )
    workdir: str | None = Field(None, description='Working directory', title='Workdir')
    timeout: int | None = Field(30, description='Timeout in seconds', title='Timeout')


class JobResponse(BaseModel):
    """
    Response for job status polling.
    """

    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    status: JobStatus = Field(..., description='Current status')
    stdout: str | None = Field('', description='Standard output so far', title='Stdout')
    stderr: str | None = Field('', description='Standard error so far', title='Stderr')
    return_code: int | None = Field(
        None, description='Exit code if completed', title='Return Code'
    )
    error: str | None = Field(
        None, description='Error message if failed', title='Error'
    )
