# generated by datamodel-codegen:
#   filename:  container_schema.json
#   timestamp: 2026-02-04T08:02:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class JobRequest(BaseModel):
    """
    Unified request for async jobs.
    """

    type: str = Field(
        ..., description="Type of job: 'command' or 'script'", title='Type'
    )
    command: str | None = Field(
        None, description='Command to run (if type=command)', title='Command'
    )
    script_name: str | None = Field(
        None, description='Script to run (if type=script)', title='Script Name'
    )
    args: list[str] | None = Field(
        None, description='Arguments for script', title='Args'
    )
    workdir: str | None = Field(None, description='Working directory', title='Workdir')
    timeout: int | None = Field(30, description='Timeout in seconds', title='Timeout')


class JobStatus(Enum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class ToolName(Enum):
    write_file = 'write_file'
    edit_file = 'edit_file'
    preview_design = 'preview_design'
    verify_solution = 'verify_solution'
    search_docs = 'search_docs'
    search_parts = 'search_parts'
    preview_part = 'preview_part'
    analyze_design = 'analyze_design'
    run_command = 'run_command'
    lint_script = 'lint_script'
    start_session = 'start_session'
    stop_session = 'stop_session'
    view_file = 'view_file'


class ToolRequest(BaseModel):
    """
    Request payload for executing a tool.
    """

    tool_name: ToolName = Field(..., description='Name of the tool to execute')
    arguments: dict[str, Any] | None = Field(
        None, description='Arguments for the tool', title='Arguments'
    )


class ToolResponse(BaseModel):
    """
    Response payload from a tool execution.
    """

    output: str = Field(..., description='String output from the tool', title='Output')
    error: str | None = Field(
        None, description='Error message if execution failed', title='Error'
    )
    status: str | None = Field(
        'success', description='Status of the execution: success/error', title='Status'
    )


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class JobResponse(BaseModel):
    """
    Response for job status polling.
    """

    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    status: JobStatus = Field(..., description='Current status')
    stdout: str | None = Field('', description='Standard output so far', title='Stdout')
    stderr: str | None = Field('', description='Standard error so far', title='Stderr')
    return_code: int | None = Field(
        None, description='Exit code if completed', title='Return Code'
    )
    error: str | None = Field(
        None, description='Error message if failed', title='Error'
    )
