# generated by datamodel-codegen:
#   filename:  container_schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class JobStatus(StrEnum):
    QUEUED = 'queued'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    CANCELLED = 'cancelled'


class JobType(StrEnum):
    COMMAND = 'command'
    SCRIPT = 'script'


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class JobRequest(BaseModel):
    """
    Unified request for async jobs.
    """

    type: JobType = Field(..., description="Type of job: 'command' or 'script'")
    command: str | None = Field(
        None, description='Command to run (if type=command)', title='Command'
    )
    script_name: str | None = Field(
        None, description='Script to run (if type=script)', title='Script Name'
    )
    args: list[str] | None = Field(
        None, description='Arguments for script', title='Args'
    )
    workdir: str | None = Field(None, description='Working directory', title='Workdir')
    timeout: int | None = Field(30, description='Timeout in seconds', title='Timeout')


class JobResponse(BaseModel):
    """
    Response for job status polling.
    """

    job_id: str = Field(..., description='Unique job identifier', title='Job Id')
    status: JobStatus = Field(..., description='Current status')
    stdout: str | None = Field('', description='Standard output so far', title='Stdout')
    stderr: str | None = Field('', description='Standard error so far', title='Stderr')
    return_code: int | None = Field(
        None, description='Exit code if completed', title='Return Code'
    )
    error: str | None = Field(
        None, description='Error message if failed', title='Error'
    )
