from enum import Enum


class SimulatorBackendType(str, Enum):
    MUJOCO = "mujoco"
    GENESIS = "genesis"


class SimulationFailureMode(str, Enum):
    PART_BREAKAGE = "FAILED_PART_BREAKAGE"
    ELECTRONICS_FLUID_DAMAGE = "FAILED_ELECTRONICS_FLUID_DAMAGE"
    PHYSICS_INSTABILITY = "FAILED_PHYSICS_INSTABILITY"
    FLUID_OBJECTIVE_FAILED = "FAILED_FLUID_OBJECTIVE"
    STRESS_OBJECTIVE_EXCEEDED = "FAILED_STRESS_OBJECTIVE"
    WIRE_TORN = "FAILED_WIRE_TORN"
